name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: NPM Install
        run: |
          npm install

      - name: QA
        run: |
          npm run test

      - name: Determine Next Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.0.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "MAJOR:"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "MINOR:"
          # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "src"

      - run: |
          echo "{{ steps.semver.outputs.version }}"