name: release

on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'force publish even if there is no change'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: NPM Install
        run: |
          npm install

      - name: QA
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

      - name: Determine Next Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR:"
          minor_pattern: "MINOR:"
          version_format: "${major}.${minor}.${patch}"
          change_path: "src"

      - name: Display Version
        run: |
          echo "version: ${{ steps.semver.outputs.version }}"
          
      - name: Tag
        if: |
          steps.semver.outputs.changed == 'true'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: "${{ secrets.TOKEN }}"
          custom_tag: "${{ steps.semver.outputs.version }}"

      - name: NPM Login
        if: |
          steps.semver.outputs.changed == 'true' ||
          inputs.force_publish == 'true'
        run: |
          npm login \
            --registry=https://registry.npmjs.org/ \
            --scope=@kickthemooon \
            --always-auth \
            --auth-type=oauth \
            --oauth-token="${NPM_TOKEN}"

      - name: Publish to NPM
        if: |
          steps.semver.outputs.changed == 'true' ||
          inputs.force_publish == 'true'
        run: |
          cp package-npm.json dist/package.json
          cd dist
          npm publish
