name: release

on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'force publish even if there is no change'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: NPM Install
        run: |
          npm install

      - name: QA
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

      - name: Determine Next Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR:"
          minor_pattern: "MINOR:"
          version_format: "${major}.${minor}.${patch}"

      - name: Display Version
        run: |
          echo "version: ${{ steps.semver.outputs.version }}"
          
      - name: Tag
        if: |
          steps.semver.outputs.changed == 'true'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: "${{ secrets.TOKEN }}"
          custom_tag: "${{ steps.semver.outputs.version }}"

      - name: Prepare for Publish
        run: |
          cat package-npm.json | \
          sed "s|VERSION|v${{ steps.semver.outputs.version }}|g" > dist/package.json

      - uses: JS-DevTools/npm-publish@v1
        if: |
          steps.semver.outputs.changed == 'true' ||
          github.event.inputs.force_publish == 'true'
        with:
          token: "${{ secrets.NPM_TOKEN }}"
          package: "dist/package.json"

